meta_product_name: "Fastdemocracy"
meta_title: "Online vote made simple"
meta_description: "FastDemocracy is a vote tool designed to save you some time and allow you to keep private data really private, as it should always "
meta_image: "logo.png" # should exist in `app/assets/images/`
